/**
 * Assignment Title Collections
 * This module contains the predefined lists of titles for each assignment type.
 */

// A. Present-Tense Story Prompts (120)
export const STORY_TITLES = [
    "A Rainy Morning Surprise",
    "The Lost Wallet Lesson",
    "Midnight Train Encounter",
    "A Stranger's Smile",
    "The Garden's Secret Door",
    "A Day Without Clocks",
    "Chasing Echoes",
    "The Vanishing Letter",
    "A Whisper in the Hall",
    "Colors at Dawn",
    "The Deserted Playground",
    "Finding Fortune in Mud",
    "A Stranger at Breakfast",
    "The Silent Bell Tower",
    "Dancing in the Elevator",
    "The Moonlit Ferry",
    "The Park Bench Confession",
    "A Letter Left on the Windshield",
    "The Bakery's Hidden Ingredient",
    "Conversations with Shadows",
    "A Painting That Talks",
    "The Elevator That Stops",
    "Midnight at the Bookshop",
    "The Old Key in the Attic",
    "Singing in the Rainstorm",
    "A Traffic Jam Miracle",
    "Sunrise on the Rooftop",
    "The Café at the Corner",
    "A Bicycle and a Promise",
    "The Phone That Rings Twice",
    "A Dog's Secret Visitor",
    "The Tree That Whispers",
    "The Mirror in the Basement",
    "An Unexpected Compliment",
    "The Market Stall Mystery",
    "Lost in the Subway",
    "The Day the Music Stopped",
    "A Raincoat and a Stranger",
    "The Park Fountain's Gift",
    "Conversations with a Photograph",
    "The Library at Night",
    "The Keychain on the Bench",
    "Sunrise and a Paper Boat",
    "A Shadow in the Alley",
    "The Neighbor's Hidden Garden",
    "A Single Red Balloon",
    "The Street Musician's Tune",
    "A Letter in a Bottle",
    "The Clock That Ticks Backward",
    "Singing with Strangers",
    "The Whispering Wind Chime",
    "A Delivery at Midnight",
    "The Map Without an X",
    "The Neon Sign Flicker",
    "A Stranger's Lost Umbrella",
    "The Corner Bookstore Chat",
    "The Rooftop Lantern",
    "The Taxi Driver's Tale",
    "A Red Scarf in Winter",
    "The Note Under the Door",
    // New 60 titles below
    "The Cat That Disappears at Noon",
    "A Silence Too Loud",
    "The Door That Opens to Yesterday",
    "The Ice Cream Cart Mystery",
    "Voices Through the Vents",
    "A Ghost in the Cafeteria",
    "The Boy Who Paints Dreams",
    "A Rose Left on the Pavement",
    "The Window That Watches",
    "A Melody in the Mist",
    "When the Sky Falls Orange",
    "Tea with a Time Traveler",
    "The Broken Clock That Speaks",
    "The Bench That Tells Stories",
    "A Stranger Who Knows Your Name",
    "The Festival That Never Ends",
    "Mirrors in the Tunnel",
    "A Taxi That Takes You Back",
    "A Photograph That Changes",
    "The Library That Moves",
    "Rain That Falls in One Spot",
    "A Notebook That Writes Back",
    "The Echo in Apartment 8B",
    "Beneath the Purple Sky",
    "The Garden Grown Overnight",
    "The Room With No Corners",
    "The Train That Ignores Time",
    "Whispers Behind the Curtain",
    "A Puddle That Reflects Memories",
    "The Street That Rearranges",
    "A Stranger's Familiar Face",
    "Umbrellas and Secrets",
    "The Tune Only Kids Can Hear",
    "When Everyone Vanishes",
    "The Missing Hour",
    "Letters from a Parallel Self",
    "Dust That Remembers Names",
    "A Box That Grows Heavier",
    "The Cafe with No Door",
    "Shoes Outside the Window",
    "The Stranger Who Stopped Time",
    "The Park Where No One Ages",
    "The Dog That Recites Poetry",
    "The Fire That Glows Cold",
    "Raindrops That Float Upward",
    "The Puzzle Wall",
    "When You Forget Your Own Shadow",
    "A Raincoat from the Future",
    "The Sleepless Streetlight",
    "The Stranger with Two Reflections",
    "A Ticket to Nowhere",
    "The Voice from the Lamp Post",
    "The Midnight Umbrella Exchange",
    "A Fire Alarm with No Fire",
    "The Diary That Predicts",
    "A House That Rearranges",
    "Sunset with Strangers",
    "The Vanishing Bus Stop",
    "Footsteps on the Ceiling",
    "The Letter With No Words"
];

// B. Communication-Skills Essay Topics (120)
export const ESSAY_TITLES = [
    "Empathy in Online Chats",
    "Body Language on Video Calls",
    "Listening in the Age of Distraction",
    "Nonverbal Cues Over Text",
    "Storytelling in Virtual Meetings",
    "Building Trust Remotely",
    "Managing Digital Misunderstandings",
    "The Rise of Asynchronous Communication",
    "Balancing Formality and Friendliness",
    "Email Etiquette Today",
    "Crafting Clear Subject Lines",
    "Tone and Emojis in Business",
    "Cultural Sensitivity Online",
    "Networking Through Social Media",
    "Feedback in Remote Teams",
    "Conflict Resolution via Chat",
    "Presentation Skills on Zoom",
    "The Power of Visual Aids",
    "Encouraging Participation Digitally",
    "Articulating Ideas in Podcasts",
    "Podcasts vs. Blogs: Clarity",
    "Writing for Global Audiences",
    "Virtual Reality and Connection",
    "AI Translators and Authenticity",
    "Digital Body Language",
    "Maintaining Professionalism Remotely",
    "Bridging Generations Online",
    "Storyboarding for Webinars",
    "Crafting a Memorable LinkedIn Post",
    "Authentic Voice on Twitter",
    "Engaging Followers on Instagram",
    "Brand Tone Across Platforms",
    "Crisis Communication Online",
    "Building Community in Forums",
    "Moderating Digital Debates",
    "Empathy in Customer Chats",
    "Voice Assistants and Clarity",
    "Accessibility in Digital Content",
    "Live Streaming Etiquette",
    "Virtual Team–Building Exercises",
    "Persuasion in Email Campaigns",
    "Conversational AI vs. Human Touch",
    "Managing Group Chats",
    "The Role of Micro-learning Modules",
    "Feedback Culture in Remote Work",
    "Nurturing Relationships Digitally",
    "Quiet Quitting and Communication",
    "Maintaining Boundaries Online",
    "Visual Storytelling in Slides",
    "Personal Branding via Websites",
    "Digital Listening Skills",
    "Text Speak vs. Formal Writing",
    "Building Rapport on Calls",
    "Crafting an Elevator Pitch Online",
    "Managing Expectations Remotely",
    "The Psychology of Click-through Rates",
    "Collaborative Note-taking Tools",
    "Virtual Reality for Empathy",
    "Balancing Speed and Accuracy",
    "Humanizing Automated Replies",
    // New 60 titles below
    "Emotional Intelligence in Group Chats",
    "Digital Silence: When Not to Respond",
    "How to Be Persuasive Without Sounding Pushy",
    "Using Humor in Online Communication",
    "The Art of Giving Virtual Compliments",
    "Communication Fatigue in the Zoom Era",
    "The Disappearance of Pauses",
    "Small Talk in Large Webinars",
    "Breaking Ice in Digital Interviews",
    "The Role of Silence in Chats",
    "When to Use Voice Notes",
    "Eye Contact and Screen Fatigue",
    "Constructive Criticism Online",
    "Building a Presence Without Physical Presence",
    "How to Ask Better Questions Online",
    "The Psychology of Typing Indicators",
    "Overcoming Misinterpretations in Text",
    "Using Whiteboards Effectively in Meetings",
    "Learning to Speak Less and Mean More",
    "Digital Apologies: Do They Work?",
    "How Online Trolls Affect Public Communication",
    "Using Memes as Communication Tools",
    "The Rise of GIFs in Conversations",
    "Professionalism in Group DMs",
    "Why Tone Is Everything in a Tweet",
    "Creating Trust with Video Messages",
    "Voice Tone vs. Word Choice",
    "Ethical Persuasion in Influencer Marketing",
    "Using Data to Enhance Arguments",
    "Effective Online Interviewing Skills",
    "The Power of First Impressions in Digital Profiles",
    "Bringing Back Handwritten Communication",
    "Personalization in Email Marketing",
    "Sarcasm in Digital Messages",
    "The Impact of Filters on Authenticity",
    "Digital Storytelling for Advocacy",
    "Trust-Building in Remote Leadership",
    "Transparency in Team Communications",
    "Using Communication Tools Mindfully",
    "Disagreeing Without Offending Online",
    "Politeness vs. Directness in Emails",
    "Remote Feedback and Motivation",
    "Digital Etiquette in Multicultural Teams",
    "Keeping Attention in Long Zoom Calls",
    "Tonal Shifts Across Cultures",
    "Creating Connection Without Cameras",
    "Social Listening in Brand Engagement",
    "Are Emojis Unprofessional?",
    "Crafting Community Through Discord",
    "Managing Miscommunication During Crises",
    "The Role of Sound Design in Podcasts",
    "Subtext in Messaging Platforms",
    "How Shorter Replies Can Signal Power",
    "Is Overcommunication Hurting Teams?",
    "Reactions vs. Replies in Group Chats",
    "Avoiding Ghosting in Digital Networks",
    "Communication Lessons from Online Games"
];

// C. AI-Paragraph Topics (60)
export const PARA_TITLES = [
    "AI in Everyday Gadgets",
    "Machine Learning in Healthcare",
    "Chatbots in Customer Service",
    "Self-Driving Cars Today",
    "AI and Climate Modeling",
    "Facial Recognition Ethics",
    "AI-Generated Art",
    "Recommendation Engines",
    "AI in Fraud Detection",
    "Natural Language Understanding",
    "AI in Financial Trading",
    "Personalized Learning Systems",
    "AI and Mental Health",
    "Robotics in Manufacturing",
    "AI for Disaster Response",
    "Smart Home Assistants",
    "Predictive Text Tools",
    "AI in Agriculture",
    "Sentiment Analysis Online",
    "AI-Driven Healthcare Diagnostics",
    "Neural Networks Basics",
    "AI in Supply Chain",
    "Automated Journalism",
    "AI-Enhanced Music Composition",
    "Virtual Personal Trainers",
    "Deepfake Technology",
    "AI in Space Exploration",
    "Gamification with AI",
    "AI-Powered Translation",
    "Ethics of Autonomous Weapons",
    "AI in Smart Cities",
    "Emotion Recognition Tech",
    "AI in Retail Analytics",
    "Voice-Activated Controls",
    "AI-Based Drug Discovery",
    "AI in Sports Analytics",
    "Computer Vision Trends",
    "AI in Cybersecurity",
    "Adaptive Traffic Systems",
    "AI and Privacy Concerns",
    "Machine Learning Workflows",
    "AI-Assisted Creativity",
    "AI in Legal Research",
    "Explainable AI Importance",
    "AI in Personalized Marketing",
    "Quantum Computing and AI",
    "AI for Wildlife Conservation",
    "Reinforcement Learning",
    "AI in Education",
    "AI-Enabled Fraud Prevention",
    "Future of Human-AI Collaboration",
    "AI in E-Commerce",
    "AI-Driven Weather Forecasts",
    "AI for Energy Efficiency",
    "AI in Telecommunications",
    "Bias in Machine Learning",
    "AI in Virtual Reality",
    "AI-Powered Accessibility Tools",
    "AI for Language Preservation",
    "AI-Enhanced User Interfaces"
]; 